### ISSUE TITLE
Export Button Doesn't Work?

### ISSUE THREAD

**Issue by SeaGnash** [coandco/TSSSF-Frontend#16]
When I click the export button after I'm finished with a card, nothing seems to happen at all. I'm not sure if it's not working, or there's just something I'm missing. I'm using Firefox if that makes a difference of any kind.

**Comment by coandco** [comment]
What URL are you using this from?  Can you link me to it?

**Comment by SeaGnash** [comment]
https://latent-logic.github.io/TSSSF-Frontend/#v1:AoewdgngBlC2CGAbApgM2QlBCArmAlgMYgBOYMFA7sgEYC0A5ictAOoCiAQgAQDCAggCUAIgG5uAFQDKMgGLcaEbgAlSJfDRTdgyEAActAcXixkAZwB03bvxIAXBUoCqYANZgQlMBaA=

**Comment by Latent-Logic** [comment]
Interesting, https is broken. We'll investigate soon, but for now try it with http instead:
http://latent-logic.github.io/TSSSF-Frontend/#v1:AoewdgngBlC2CGAbApgM2QlBCArmAlgMYgBOYMFA7sgEYC0A5ictAOoCiAQgAQDCAggCUAIgG5uAFQDKMgGLcaEbgAlSJfDRTdgyEAActAcXixkAZwB03bvxIAXBUoCqYANZgQlMBaA=

**Comment by SeaGnash** [comment]
Thank you!

**Comment by Latent-Logic** [comment]
Both http and https should work now with the latent-logic.github.io page. Thanks for letting us know about the issue!

**Comment by SG-7** [comment]
I downloaded this repo, so I could use custom expansion symbols, and the export button doesn't work. Am I just out of luck or is there a way to fix this?

**Comment by Latent-Logic** [comment]
@SG-7 please open a separate issue, this one is specifically about an issue that happened with https://latent-logic.github.io/TSSSF-Frontend . However TL;DR you need to run a backend for rendering cards that is running https://github.com/Latent-Logic/CardMachine/tree/ssf_master
