### ISSUE TITLE
Earth pony symbol is incorrectly translated to {earthpony} on field change.

### ISSUE THREAD

**Issue by querkmachine** [coandco/TSSSF-Frontend#17]
The `{earth}` symbol keyword seems to be incorrectly translated to read `{earthpony}` in some situations.

![thats-a-bug](https://cloud.githubusercontent.com/assets/1253214/18233881/0efa0d98-72ec-11e6-9684-b4d0b60afba8.gif)

**Creating a new card:**
1. Create a new card.
2. In the card body, type `{earth}` and click/tab away to a different field. 
3. Expected result: Text is transformed to earth pony symbol.<br>Actual result: Text is transformed to read `{earthpony}`. 

**Modifying a card:**
1. Change any of the content in a card body which contains the earth pony symbol and click/tab away to a different field. 
2. Expected result: The earth pony symbol is retained.<br>Actual result: The earth pony symbol is transformed to read `{earthpony}`. 

**Loading a saved card:**
1. Load a saved card which contains the earth pony symbol (e.g. https://is.gd/GdobeI) 
2. Expected result: The earth pony symbol is retained.<br>Actual result: The earth pony symbol is transformed to read `{earthpony}`.

**Comment by coandco** [comment]
Thanks a ton for your clear and well-researched bug report.  I've committed a fix, and will be propagating said fix to the various known installations of the TSSSF Frontend over the course of the next day or so.

**Comment by Latent-Logic** [comment]
This has now been fixed on http://latent-logic.github.io/TSSSF-Frontend, thanks again for the great bug report!

**Comment by querkmachine** [comment]
No problem folks, I know how annoying a vague bug report can be. 
Thank you for fixing it so quickly!
