### ISSUE TITLE
Can't import images from Imgur

### ISSUE THREAD

**Issue by n-a-larson** [coandco/TSSSF-Frontend#22]
The main page accepts links from Imgur and loads a preview into the card frame, but this image does not appear on the exported card. This issue has been duplicated on Firefox and Chrome.

Example card: https://is.gd/9Y3LCV

**Comment by coandco** [comment]
Did some debugging and it looks like imgur implemented drastically lower rate limits.  When your browser loads the image in the preview, imgur sends the image just fine, but when the hosted backend attempts the same thing it's getting an HTTP 429 Too Many Requests.  Not sure there's much we can do about it.  Self-hosted versions of the card generator should work fine.

**Comment by coandco** [comment]
Actually, found a fix, thanks to @Latent-Logic pointing out https://github.com/aliparlakci/bulk-downloader-for-reddit/issues/864 -- setting one's user agent to curl seems to fix the issue.  I haven't worked on this project for a while, so I'm trying to dredge up where the fix needs to be committed.

**Comment by coandco** [comment]
@Latent-Logic pushed the fix to https://github.com/Latent-Logic/CardMachine/commit/668c7368868992132adc338baa766dc7f0e39d94
