### ISSUE TITLE
Card Art UX

### ISSUE THREAD

**Issue by MaskedRetriever** [coandco/TSSSF-Frontend#6]
Not technically a bug, but the UX on card art could use the following improvements:
1: A field inside the card art area to paste image links (in keeping with how beautiful and intuitive all the other fields are to fill in)
2: Feedback to alert a user that links to webpages with images aren't enough, that you need the direct link.  (An image scraper is a nice-to-have but probably way harder and not necessary if the user can be quickly alerted that they needed to just paste a .png link.)

**Comment by coandco** [comment]
I'm having trouble visualizing how the field inside the card-art area would work, so absent a more concrete suggestion, I'm going to pass on that for now (it require more UX experience than I have to implement).

However, I do think that specific feedback reminding the user to paste actual image links is a good idea, so I've implemented it.  Thanks for the suggestion!
