### ISSUE TITLE
Newline in flavor text gets converted to literal '\' 'n'

### ISSUE THREAD

**Issue by Latent-Logic** [coandco/TSSSF-Frontend#7]
If you type a newline, select outside the flavor field, and then select it again, you'll see that it's still a \n character. This issue doesn't seem to occur in any other field.

**Comment by coandco** [comment]
I was misunderstanding how Javascript's .replace() function worked -- I didn't realize that without the "g" flag it only replaced the first instance.  This led to some buggy behavior where the first newline in a card string would get replaced, but not the rest.
